# Generated by Django 6.0.6 on 2026-08-11 19:13

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('permissoes', models.JSONField(blank=True, default=list)),
                ('escopo_padrao', models.CharField(choices=[('proprio', 'Próprio'), ('equipe', 'Equipe (liderados diretos e indiretos)'), ('departamento', 'Departamento'), ('unidade', 'Unidade'), ('global', 'Global')], default='proprio', max_length=20)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Delegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('de_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('para_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('papeis', models.ManyToManyField(blank=True, help_text='Vazio = delega todos os papéis vigentes do delegante.', related_name='delegacoes', to='identidade.papel')),
            ],
            options={
                'verbose_name': 'delegação',
                'verbose_name_plural': 'delegações',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['para_user', 'inicio', 'fim'], name='idn_deleg_para_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, db_index=True, max_length=30)),
                ('centro_custo_codigo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('ferias', 'Em férias'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], db_index=True, default='ativo', max_length=20)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='identidade.departamento')),
                ('gestor', models.ForeignKey(blank=True, help_text='Quem esta pessoa reporta. Define o escopo `equipe`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lotacao', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'lotação',
                'verbose_name_plural': 'lotações',
                'indexes': [models.Index(fields=['gestor'], name='idn_lotacao_gestor_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('proprio', 'Próprio'), ('equipe', 'Equipe (liderados diretos e indiretos)'), ('departamento', 'Departamento'), ('unidade', 'Unidade'), ('global', 'Global')], max_length=20)),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_papel', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='identidade.departamento')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='identidade.papel')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'atribuição de papel',
                'verbose_name_plural': 'atribuições de papel',
                'ordering': ['-vigencia_inicio'],
                'indexes': [models.Index(fields=['user', 'vigencia_inicio', 'vigencia_fim'], name='idn_atrib_vigencia_idx')],
                'constraints': [models.UniqueConstraint(models.F('user'), models.F('papel'), models.F('escopo'), django.db.models.functions.comparison.Coalesce('unidade', models.Value(0)), django.db.models.functions.comparison.Coalesce('departamento', models.Value(0)), models.F('vigencia_inicio'), name='idn_atribuicao_unica')],
            },
        ),
    ]
