# Generated by Django 6.0.7 on 2026-08-13 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Como aparece na lotação da pessoa. É a chave de ligação.', max_length=20, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=120)),
                ('orcamento_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio significa não definido, que é diferente de zero.', max_digits=14, null=True, verbose_name='orçamento mensal')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('competencia', models.DateField(db_index=True, help_text='Primeiro dia do mês de referência.')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financas.centrocusto')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['-competencia', '-criado_em'],
                'indexes': [models.Index(fields=['centro_custo', 'competencia'], name='fin_lanc_cc_idx')],
            },
        ),
    ]
