# Generated by Django 6.0.8 on 2026-09-03 01:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('vigente', 'Vigente'), ('encerrado', 'Encerrado')], db_index=True, default='rascunho', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('vigorou_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='financas.centrocusto')),
                ('vigorou_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_vigorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orçamento anual',
                'verbose_name_plural': 'orçamentos anuais',
                'ordering': ['-ano', 'centro_custo__codigo'],
            },
        ),
        migrations.CreateModel(
            name='LinhaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='financas.orcamentoanual')),
            ],
            options={
                'verbose_name': 'linha de orçamento',
                'verbose_name_plural': 'linhas de orçamento',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='RevisaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('motivo', models.CharField(max_length=300)),
                ('deltas', models.JSONField(default=dict)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_de_orcamento', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='financas.orcamentoanual')),
            ],
            options={
                'verbose_name': 'revisão orçamentária',
                'verbose_name_plural': 'revisões orçamentárias',
                'ordering': ['orcamento', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='orcamentoanual',
            constraint=models.UniqueConstraint(fields=('centro_custo', 'ano'), name='fin_orcamento_um_por_ano'),
        ),
        migrations.AddConstraint(
            model_name='linhaorcamento',
            constraint=models.UniqueConstraint(fields=('orcamento', 'mes'), name='fin_linha_um_por_mes'),
        ),
        migrations.AddConstraint(
            model_name='linhaorcamento',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='fin_linha_mes_no_calendario'),
        ),
        migrations.AddConstraint(
            model_name='revisaoorcamento',
            constraint=models.UniqueConstraint(fields=('orcamento', 'numero'), name='fin_revisao_numero_unico'),
        ),
    ]
