# Generated by Django 6.0.7 on 2026-08-13 14:50

import contas.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Identificador da conta. Vem do SSO quando ele estiver ligado.', max_length=254, unique=True, verbose_name='e-mail corporativo')),
                ('nome', models.CharField(blank=True, max_length=160, verbose_name='nome completo')),
                ('entra_oid', models.CharField(blank=True, db_index=True, default='', help_text='Identificador imutável da pessoa no tenant M365.', max_length=64, verbose_name='object id no Entra ID')),
                ('upn', models.CharField(blank=True, default='', help_text='Como o M365 chama a pessoa. Pode divergir do e-mail.', max_length=254, verbose_name='user principal name')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque em vez de apagar: apagar a conta levaria embora, em cascata, a trilha de quem aprovou o quê.', verbose_name='ativa')),
                ('is_staff', models.BooleanField(default=False, help_text='Nunca derivado do SSO — concessão explícita, sempre.', verbose_name='acessa o admin')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome', 'email'],
            },
            managers=[
                ('objects', contas.models.PessoaManager()),
            ],
        ),
    ]
