# Generated by Django 6.0.7 on 2026-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Opcional. Sem foto, o portal usa as iniciais do nome.', upload_to='avatares/', verbose_name='foto de perfil'),
        ),
    ]
