# Generated by Django 6.0.8 on 2026-09-02 10:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual')], max_length=30, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('cadencia_esperada', models.CharField(blank=True, max_length=80)),
                ('idade_maxima_aceitavel', models.DurationField(blank=True, default=datetime.timedelta(days=1, seconds=7200), null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=120)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'fonte de dados',
                'verbose_name_plural': 'fontes de dados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('terminada_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('falha', 'Falha')], db_index=True, default='em_andamento', max_length=20)),
                ('janela_de', models.DateField(blank=True, null=True)),
                ('janela_ate', models.DateField(blank=True, null=True)),
                ('lidos', models.PositiveIntegerField(default=0)),
                ('criados', models.PositiveIntegerField(default=0)),
                ('atualizados', models.PositiveIntegerField(default=0)),
                ('ignorados', models.PositiveIntegerField(default=0)),
                ('rejeitados', models.PositiveIntegerField(default=0)),
                ('erro_resumo', models.CharField(blank=True, max_length=300)),
                ('log', models.TextField(blank=True)),
                ('simulacao', models.BooleanField(db_index=True, default=False)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='cargas.fontedados')),
            ],
            options={
                'verbose_name': 'execução de carga',
                'verbose_name_plural': 'execuções de carga',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraPrecedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(db_index=True, max_length=40)),
                ('campo', models.CharField(max_length=40)),
                ('fonte_vencedora', models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual')], max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('justificativa', models.TextField(blank=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'regra de precedência',
                'verbose_name_plural': 'regras de precedência',
                'ordering': ['entidade', 'campo', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('entidade', 'campo', 'fonte_vencedora'), name='crg_precedencia_unica')],
            },
        ),
        migrations.CreateModel(
            name='Divergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(db_index=True, max_length=40)),
                ('chave_externa', models.CharField(db_index=True, max_length=120)),
                ('campo', models.CharField(max_length=40)),
                ('fonte_a', models.CharField(max_length=30)),
                ('valor_a', models.CharField(max_length=200)),
                ('fonte_b', models.CharField(max_length=30)),
                ('valor_b', models.CharField(max_length=200)),
                ('fonte_vencedora', models.CharField(blank=True, max_length=30)),
                ('detectada_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolvida_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias', to='cargas.execucaocarga')),
            ],
            options={
                'verbose_name': 'divergência entre fontes',
                'verbose_name_plural': 'divergências entre fontes',
                'ordering': ['-detectada_em'],
                'indexes': [models.Index(fields=['resolvida_em', '-detectada_em'], name='crg_divergencia_abertas_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='execucaocarga',
            index=models.Index(fields=['fonte', 'status', '-terminada_em'], name='crg_execucao_frescor_idx'),
        ),
    ]
