# Generated by Django 6.0.8 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontedados',
            name='chave',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='regraprecedencia',
            name='fonte_vencedora',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], max_length=30),
        ),
    ]
