# Generated by Django 6.0.8 on 2026-09-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='avaliacaocliente',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='competenciaresultado',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='marcoprojeto',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='quadropessoas',
            name='fonte',
            field=models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='EditalPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30)),
                ('chave_externa', models.CharField(db_index=True, max_length=120)),
                ('carga_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now=True, db_index=True)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64)),
                ('numero_controle', models.CharField(db_index=True, max_length=60)),
                ('objeto', models.TextField()),
                ('orgao', models.CharField(blank=True, max_length=200)),
                ('unidade', models.CharField(blank=True, max_length=200)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('modalidade', models.CharField(blank=True, max_length=80)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('abertura_proposta', models.DateTimeField(blank=True, null=True)),
                ('encerramento_proposta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('termo_casado', models.CharField(blank=True, db_index=True, max_length=80)),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'edital público',
                'verbose_name_plural': 'editais públicos',
                'ordering': ['encerramento_proposta'],
                'constraints': [models.UniqueConstraint(fields=('fonte', 'chave_externa'), name='res_edital_origem_unica')],
            },
        ),
    ]
