# Generated by Django 6.0.8 on 2026-09-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_apontamento_fonte_alter_avaliacaocliente_fonte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'área',
                'verbose_name_plural': 'áreas',
                'ordering': ['ordem', 'codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo', 'sem-area'), _negated=True), name='res_area_codigo_reservado')],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='resultados.area'),
        ),
    ]
