# Generated by Django 6.0.8 on 2026-09-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_servico_como_se_contrata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('natureza', models.CharField(choices=[('receita', 'Receita'), ('imposto', 'Imposto sobre faturamento'), ('custo', 'Custo direto'), ('indireto', 'Custo indireto'), ('financeiro', 'Resultado financeiro'), ('nao_operacional', 'Não operacional')], db_index=True, max_length=20)),
                ('degrau_dre', models.CharField(blank=True, choices=[('receita_bruta', 'Receita Bruta'), ('impostos', 'Impostos'), ('pessoal', 'Pessoal'), ('encargos', 'Encargos e Provisões'), ('beneficios', 'Benefícios'), ('materiais', 'Materiais e Insumos'), ('servicos_pj', 'Serviços PJ'), ('transportes', 'Transportes'), ('demais', 'Demais'), ('indireto', 'Indireto')], db_index=True, max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='resultados.contacontabil')),
            ],
            options={
                'verbose_name': 'conta contábil',
                'verbose_name_plural': 'contas contábeis',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPorConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('sankhya', 'Sankhya'), ('monday', 'monday.com'), ('iconnect_platform', 'iConnect Platform'), ('csv', 'Carga por arquivo'), ('manual', 'Lançamento manual'), ('pncp', 'PNCP · contratações públicas')], db_index=True, max_length=30)),
                ('chave_externa', models.CharField(db_index=True, max_length=120)),
                ('carga_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now=True, db_index=True)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64)),
                ('centro_custo', models.CharField(db_index=True, max_length=20)),
                ('ano', models.PositiveSmallIntegerField(db_index=True)),
                ('mes', models.PositiveSmallIntegerField(db_index=True)),
                ('codigo_origem', models.CharField(db_index=True, max_length=20)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ajustes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='resultados.contacontabil')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='resultados.contrato')),
            ],
            options={
                'verbose_name': 'resultado por conta',
                'verbose_name_plural': 'resultados por conta',
                'ordering': ['ano', 'mes', 'codigo_origem'],
            },
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['pai', 'ordem'], name='res_conta_grupo_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoporconta',
            index=models.Index(fields=['ano', 'mes', 'centro_custo'], name='res_conta_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadoporconta',
            index=models.Index(fields=['contrato', 'ano', 'mes'], name='res_conta_ctr_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadoporconta',
            constraint=models.UniqueConstraint(fields=('fonte', 'chave_externa'), name='res_conta_origem_unica'),
        ),
    ]
