# Generated by Django 6.0.8 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_plano_de_contas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacontabil',
            name='natureza',
            field=models.CharField(choices=[('receita', 'Receita'), ('imposto', 'Imposto sobre faturamento'), ('custo', 'Custo'), ('financeiro', 'Resultado financeiro'), ('nao_operacional', 'Não operacional')], db_index=True, max_length=20),
        ),
    ]
