# Generated by Django 6.0.8 on 2026-09-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_natureza_sem_indireto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='escopo',
            field=models.TextField(blank=True),
        ),
    ]
