# Generated by Django 6.0.8 on 2026-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0007_contrato_escopo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaresultado',
            name='custo_indireto_orcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='competenciaresultado',
            name='ebitda_orcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='competenciaresultado',
            name='impostos_orcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
