# Generated by Django 6.0.8 on 2026-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0008_tres_orcados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaresultado',
            name='custo_direto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='competenciaresultado',
            name='margem_contribuicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
