# Generated by Django 6.0.8 on 2026-09-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0009_custo_anulavel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apontamento',
            name='res_apontamento_cc_unico',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to='resultados.contrato'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.UniqueConstraint(condition=models.Q(('contrato__isnull', True)), fields=('centro_custo', 'ano', 'mes'), name='res_apontamento_cc_unico'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.UniqueConstraint(condition=models.Q(('contrato__isnull', False)), fields=('contrato', 'centro_custo', 'ano', 'mes'), name='res_apontamento_contrato_unico'),
        ),
    ]
