# Generated by Django 6.0.6 on 2026-08-07 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comunicado', 'Comunicado'), ('noticia', 'Notícia')], db_index=True, default='comunicado', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, help_text='Uma linha, exibida no card do Portal.', max_length=300)),
                ('corpo', models.TextField(blank=True)),
                ('prioridade', models.IntegerField(choices=[(0, 'Normal'), (1, 'Atenção'), (2, 'Urgente')], default=0)),
                ('fixado', models.BooleanField(default=False, help_text='Fixa no topo da lista.')),
                ('publicado', models.BooleanField(db_index=True, default=False)),
                ('publicar_em', models.DateTimeField(default=django.utils.timezone.now, help_text='Data futura agenda a publicação.')),
                ('expira_em', models.DateTimeField(blank=True, help_text='Em branco, não expira.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-fixado', '-publicar_em'],
                'indexes': [models.Index(fields=['tipo', 'publicado', '-publicar_em'], name='wks_pub_listagem_idx')],
            },
        ),
    ]
