# Generated by Django 6.0.6 on 2026-08-11 20:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, max_length=40)),
                ('origem_id', models.CharField(blank=True, help_text='Id do objeto no domínio de origem.', max_length=40)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('centro_custo_codigo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('situacao', models.CharField(choices=[('aguardando', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('devolvida', 'Devolvida'), ('cancelada', 'Cancelada')], db_index=True, default='aguardando', max_length=20)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_aprovacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de aprovação',
                'verbose_name_plural': 'solicitações de aprovação',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EtapaAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('devolvida', 'Devolvida'), ('pulada', 'Pulada')], db_index=True, default='pendente', max_length=20)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('motivo_pulo', models.CharField(blank=True, max_length=200)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_como_aprovador', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_decididas', to=settings.AUTH_USER_MODEL)),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_aprovacao', to='identidade.papel')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workspace.solicitacaoaprovacao')),
            ],
            options={
                'verbose_name': 'etapa de aprovação',
                'verbose_name_plural': 'etapas de aprovação',
                'ordering': ['solicitacao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, default='*', help_text='`*` vale para todos. `fin.reembolso` só para reembolso.', max_length=40)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='A etapa entra quando o valor alcança este mínimo. 0 = sempre.', max_digits=12)),
                ('tipo', models.CharField(choices=[('gestor_direto', 'Gestor direto do solicitante'), ('papel', 'Quem tiver o papel'), ('nominal', 'Pessoa específica')], max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=10)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_aprovacao', to=settings.AUTH_USER_MODEL)),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_aprovacao', to='identidade.papel')),
            ],
            options={
                'verbose_name': 'regra de aprovação',
                'verbose_name_plural': 'regras de aprovação',
                'ordering': ['dominio', 'ordem', 'valor_minimo'],
                'indexes': [models.Index(fields=['dominio', 'ativa', 'ordem'], name='wks_regra_apr_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaoaprovacao',
            index=models.Index(fields=['situacao', 'criado_em'], name='wks_solic_bandeja_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoaprovacao',
            index=models.Index(fields=['dominio', 'origem_id'], name='wks_solic_origem_idx'),
        ),
        migrations.AddIndex(
            model_name='etapaaprovacao',
            index=models.Index(fields=['aprovador', 'situacao'], name='wks_etapa_bandeja_idx'),
        ),
        migrations.AddConstraint(
            model_name='etapaaprovacao',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'ordem'), name='wks_etapa_ordem_unica'),
        ),
    ]
