# Generated by Django 6.0.6 on 2026-08-11 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_solicitacaoaprovacao_etapaaprovacao_regraaprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, max_length=40)),
                ('origem_id', models.CharField(blank=True, max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('centro_custo_codigo', models.CharField(db_index=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('competencia', models.DateField(db_index=True, help_text='Primeiro dia do mês de referência.')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo (aprovado, não pago)'), ('baixado', 'Baixado (movimentação lançada)'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=20)),
                ('movimentacao_id', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('baixado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to='workspace.solicitacaoaprovacao')),
            ],
            options={
                'verbose_name': 'compromisso',
                'verbose_name_plural': 'compromissos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['centro_custo_codigo', 'competencia', 'situacao'], name='wks_comp_cc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('solicitacao__isnull', False)), fields=('solicitacao',), name='wks_comp_uma_por_solicitacao')],
            },
        ),
    ]
