# Generated by Django 6.0.6 on 2026-08-11 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_compromisso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao_curta', models.CharField(blank=True, help_text='Uma linha, exibida no card do catálogo.', max_length=200)),
                ('grupo', models.CharField(choices=[('equipamento', 'Equipamento e acesso'), ('trabalho', 'Trabalho e ausência'), ('dinheiro', 'Dinheiro'), ('viagem', 'Viagem'), ('espaco', 'Espaço e material'), ('desenvolvimento', 'Desenvolvimento'), ('juridico', 'Jurídico')], db_index=True, max_length=20)),
                ('icone', models.CharField(default='grid', max_length=30)),
                ('dominio', models.CharField(help_text='Domínio de destino: fin.reembolso, rh.ferias, com.requisicao…', max_length=40)),
                ('prazo_prometido_dias', models.PositiveSmallIntegerField(default=5, help_text='Usado só enquanto não há histórico. Depois de 5 conclusões o card mostra o prazo REAL medido (P50) — é o que constrói confiança.')),
                ('exige_valor', models.BooleanField(default=False)),
                ('exige_centro_custo', models.BooleanField(default=False)),
                ('campos', models.JSONField(blank=True, default=list)),
                ('permissao', models.CharField(blank=True, help_text='Vazio = qualquer funcionário pode pedir.', max_length=60)),
                ('limite_auto_aprovacao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'item do catálogo',
                'verbose_name_plural': 'itens do catálogo',
                'ordering': ['grupo', 'ordem', 'nome'],
                'indexes': [models.Index(fields=['ativo', 'grupo', 'ordem'], name='wks_item_cat_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('centro_custo_codigo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('situacao', models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluída'), ('devolvida', 'Devolvida'), ('cancelada', 'Cancelada')], db_index=True, default='aguardando_aprovacao', max_length=25)),
                ('auto_aprovada', models.BooleanField(default=False)),
                ('motivo_devolucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('aprovacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico', to='workspace.solicitacaoaprovacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='workspace.itemcatalogo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_servico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de serviço',
                'verbose_name_plural': 'solicitações de serviço',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['solicitante', 'situacao'], name='wks_svc_minhas_idx'), models.Index(fields=['item', 'situacao'], name='wks_svc_item_idx')],
            },
        ),
    ]
