# Generated by Django 6.0.6 on 2026-08-12 13:19

import django.db.models.deletion
import workspace.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_itemcatalogo_solicitacaoservico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(db_index=True, max_length=50)),
                ('arquivo', models.FileField(max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_do_anexo)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveBigIntegerField(help_text='Bytes.')),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_portal', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='workspace.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'anexo de solicitação',
                'verbose_name_plural': 'anexos de solicitação',
                'ordering': ['campo', 'criado_em'],
                'indexes': [models.Index(fields=['solicitacao', 'campo'], name='wks_anexo_sol_idx')],
            },
        ),
    ]
