# Generated by Django 6.0.6 on 2026-08-12 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('pop', 'POP — procedimento operacional'), ('politica', 'Política'), ('norma', 'Norma'), ('instrucao', 'Instrução de trabalho'), ('manual', 'Manual')], db_index=True, default='pop', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, help_text='Uma linha. Aparece na lista.', max_length=300)),
                ('corpo', models.TextField(blank=True)),
                ('versao', models.CharField(default='1.0', help_text='Texto livre — é o formato que a norma ISO usa (1.0, 1.2, 2026-A).', max_length=12)),
                ('publico_alvo', models.JSONField(blank=True, default=list, help_text='Sujeitos que podem ver. `["*"]` = todos. Também aceita `papel:sesmt`, `depto:3`, `unidade:1`, `pessoa:42`.')),
                ('leitura_obrigatoria', models.BooleanField(default=False, help_text='Exige confirmação de leitura, com trilha para auditoria.')),
                ('vigencia_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField(blank=True, db_index=True, help_text='Vazio = sem prazo de validade.', null=True)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('vigente', 'Vigente'), ('revogado', 'Revogado')], db_index=True, default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_workspace', to=settings.AUTH_USER_MODEL)),
                ('revoga', models.ForeignKey(blank=True, help_text='O documento que este substitui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revogado_por', to='workspace.documento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=12)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_workspace', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='workspace.documento')),
            ],
            options={
                'verbose_name': 'confirmação de leitura',
                'verbose_name_plural': 'confirmações de leitura',
                'ordering': ['-confirmado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['situacao', 'tipo', 'titulo'], name='wks_doc_vitrine_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['leitura_obrigatoria', 'situacao'], name='wks_doc_obrig_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmacaoleitura',
            index=models.Index(fields=['pessoa', 'documento'], name='wks_leitura_pessoa_idx'),
        ),
        migrations.AddConstraint(
            model_name='confirmacaoleitura',
            constraint=models.UniqueConstraint(fields=('documento', 'pessoa', 'versao'), name='wks_leitura_unica_por_versao'),
        ),
    ]
