# Generated by Django 6.0.6 on 2026-08-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(db_index=True, max_length=40)),
                ('origem_id', models.CharField(max_length=64)),
                ('origem', models.CharField(choices=[('servico', 'Serviços'), ('documento', 'Documentação'), ('comunicado', 'Comunicados'), ('noticia', 'Notícias')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField(blank=True)),
                ('url', models.CharField(max_length=300)),
                ('icone', models.CharField(blank=True, max_length=30)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'entrada do índice',
                'verbose_name_plural': 'entradas do índice',
                'ordering': ['origem', 'titulo'],
                'indexes': [models.Index(fields=['origem', 'titulo'], name='wks_indice_grupo_idx')],
                'constraints': [models.UniqueConstraint(fields=('dominio', 'origem_id'), name='wks_indice_origem_unica')],
            },
        ),
        migrations.CreateModel(
            name='SujeitoIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujeito', models.CharField(db_index=True, max_length=60)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujeitos', to='workspace.entradaindice')),
            ],
            options={
                'verbose_name': 'sujeito do índice',
                'verbose_name_plural': 'sujeitos do índice',
                'constraints': [models.UniqueConstraint(fields=('entrada', 'sujeito'), name='wks_indice_sujeito_unico')],
            },
        ),
    ]
