# Generated by Django 6.0.6 on 2026-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_indice_busca'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='termos',
            field=models.JSONField(blank=True, default=list, help_text='Como as pessoas CHAMAM isto. `laptop`, `computador`, `máquina` levam a Notebook. É o que faz o assistente de ação funcionar sem IA — e cada termo aqui é um e-mail que ninguém precisou mandar.'),
        ),
    ]
