# Generated by Django 6.0.6 on 2026-08-12 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0011_preenche_termos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('sala', 'Sala'), ('veiculo', 'Veículo'), ('equipamento', 'Equipamento')], db_index=True, default='sala', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('capacidade', models.PositiveSmallIntegerField(blank=True, help_text='Pessoas, para sala. Vazio quando não se aplica.', null=True)),
                ('duracao_maxima_horas', models.PositiveSmallIntegerField(default=8, help_text='Acima disto a reserva é recusada.')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(blank=True, help_text='Onde o recurso fica. Vazio = disponível a toda a empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fim', models.DateTimeField(db_index=True)),
                ('motivo', models.CharField(blank=True, help_text='Opcional. Quem vê a agenda entende por que o recurso está preso.', max_length=200)),
                ('situacao', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='confirmada', max_length=20)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='workspace.recurso')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('intimacao', 'Intimação ou notificação judicial'), ('multa', 'Multa ou autuação'), ('documento', 'Documento'), ('encomenda', 'Encomenda'), ('carta', 'Carta')], db_index=True, default='carta', max_length=20)),
                ('remetente', models.CharField(blank=True, max_length=160)),
                ('descricao', models.CharField(blank=True, help_text='O que é, para a pessoa reconhecer sem abrir.', max_length=200)),
                ('nome_no_envelope', models.CharField(blank=True, max_length=160)),
                ('urgente', models.BooleanField(default=False, help_text='Derivado do tipo quando há prazo legal.')),
                ('situacao', models.CharField(choices=[('aguardando', 'Aguardando retirada'), ('entregue', 'Entregue'), ('devolvida', 'Devolvida ao remetente')], db_index=True, default='aguardando', max_length=20)),
                ('recebido_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retirado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Vazio quando não foi possível identificar — é caso normal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('retirado_por', models.ForeignKey(blank=True, help_text='Quem retirou de fato — pode não ser o destinatário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_retiradas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, help_text='Onde está guardada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'correspondência',
                'verbose_name_plural': 'correspondências',
                'ordering': ['-urgente', 'recebido_em'],
                'indexes': [models.Index(fields=['destinatario', 'situacao'], name='wks_corresp_pessoa_idx'), models.Index(fields=['situacao', '-urgente', 'recebido_em'], name='wks_corresp_fila_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['ativo', 'tipo', 'nome'], name='wks_recurso_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['recurso', 'situacao', 'inicio', 'fim'], name='wks_reserva_conflito_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='wks_reserva_fim_depois_do_inicio'),
        ),
    ]
