# Generated by Django 6.0.7 on 2026-08-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_campos_de_rh_e_adiantamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='adiantamento',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando este reembolso presta contas de um adiantamento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes', to='workspace.solicitacaoservico'),
        ),
        migrations.CreateModel(
            name='AcertoAdiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('devolver', 'A pessoa devolve à empresa'), ('receber', 'A empresa paga à pessoa'), ('quitado', 'Nada a acertar')], max_length=10)),
                ('total_adiantado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gasto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dados_bancarios', models.TextField(blank=True)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('comprovante', models.OneToOneField(blank=True, help_text='Comprovante da devolução, quando sobrou dinheiro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acerto', to='workspace.anexo')),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acertos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('prestacao', models.OneToOneField(help_text='O reembolso que presta contas do adiantamento.', on_delete=django.db.models.deletion.CASCADE, related_name='acerto', to='workspace.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'acerto de adiantamento',
                'verbose_name_plural': 'acertos de adiantamento',
                'ordering': ['-confirmado_em'],
            },
        ),
        migrations.CreateModel(
            name='DespesaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(help_text='Por que esta compra foi feita.', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa', to='workspace.anexo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='workspace.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'despesa de reembolso',
                'verbose_name_plural': 'despesas de reembolso',
                'ordering': ['ordem', 'pk'],
                'indexes': [models.Index(fields=['solicitacao', 'ordem'], name='wks_despesa_idx')],
            },
        ),
    ]
