# Generated by Django 6.0.7 on 2026-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_reembolso_item_a_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='passos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itemcatalogo',
            name='valor_quando',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
