# Generated by Django 6.0.7 on 2026-08-14 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_horario_em_campo_de_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
    ]
