# Generated by Django 6.0.7 on 2026-08-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_solicitacaoservico_atendente_alter_notificacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('aprovada', 'Aprovado'), ('devolvida', 'Devolvido para quem pediu'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20)),
                ('observacao', models.CharField(blank=True, help_text='O motivo da devolução, o nome de quem assumiu, o valor do acerto.', max_length=300)),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_de_solicitacao', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='workspace.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'evento da solicitação',
                'verbose_name_plural': 'eventos da solicitação',
                'ordering': ['quando', 'pk'],
                'indexes': [models.Index(fields=['solicitacao', 'quando'], name='wks_evento_idx'), models.Index(fields=['quem', 'acao', 'quando'], name='wks_evento_quem_idx')],
            },
        ),
    ]
