# Generated by Django 6.0.7 on 2026-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0020_eventosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservico',
            name='reaberturas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventosolicitacao',
            name='acao',
            field=models.CharField(choices=[('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('aprovada', 'Aprovado'), ('devolvida', 'Devolvido para quem pediu'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('reaberta', 'Reaberto — não resolveu'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
    ]
