# Generated by Django 6.0.7 on 2026-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0022_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosolicitacao',
            name='acao',
            field=models.CharField(choices=[('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('etapa_aprovada', 'Aprovado num degrau'), ('aprovada', 'Aprovado — liberado'), ('devolvida', 'Devolvido para quem pediu'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('reaberta', 'Reaberto — não resolveu'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20),
        ),
    ]
