# Generated by Django 6.0.7 on 2026-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0024_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaaprovacao',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('devolvida', 'Devolvida'), ('rejeitada', 'Reprovada'), ('pulada', 'Pulada')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventosolicitacao',
            name='acao',
            field=models.CharField(choices=[('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('etapa_aprovada', 'Aprovado num degrau'), ('aprovada', 'Aprovado — liberado'), ('devolvida', 'Devolvido para quem pediu'), ('rejeitada', 'Reprovado'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('reaberta', 'Reaberto — não resolveu'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitacaoaprovacao',
            name='situacao',
            field=models.CharField(choices=[('aguardando', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('devolvida', 'Devolvida'), ('rejeitada', 'Reprovada'), ('cancelada', 'Cancelada')], db_index=True, default='aguardando', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='situacao',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluída'), ('devolvida', 'Devolvida'), ('rejeitada', 'Reprovada'), ('cancelada', 'Cancelada')], db_index=True, default='aguardando_aprovacao', max_length=25),
        ),
    ]
