# Generated by Django 6.0.7 on 2026-08-18 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0028_viagem_para_suprimentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=40)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('par', 'Par'), ('cx', 'Caixa'), ('m', 'Metro'), ('l', 'Litro'), ('kg', 'Quilo')], default='un', max_length=5)),
                ('controla_patrimonio', models.BooleanField(default=False)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo', 'categoria'], name='wks_material_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('reversa', 'Entrada de reversa'), ('saida', 'Saída'), ('ajuste', 'Ajuste de inventário')], db_index=True, max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_posterior', models.IntegerField()),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('dominio', models.CharField(blank=True, db_index=True, max_length=40)),
                ('origem_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('condicao', models.CharField(blank=True, choices=[('novo', 'Novo'), ('usado_bom', 'Usado — em boas condições'), ('usado_reparo', 'Usado — precisa de reparo'), ('sucata', 'Sucata')], max_length=15)),
                ('cliente', models.CharField(blank=True, max_length=120)),
                ('patrimonio', models.CharField(blank=True, db_index=True, max_length=40)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='workspace.material')),
                ('quem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='identidade.unidade')),
                ('unidade_origem', models.ForeignKey(blank=True, help_text='De qual unidade o material voltou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversas_enviadas', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-quando'],
                'indexes': [models.Index(fields=['material', 'unidade', '-quando'], name='wks_mov_razao_idx'), models.Index(fields=['tipo', '-quando'], name='wks_mov_tipo_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, help_text='Prateleira, sala, contêiner.', max_length=80)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='workspace.material')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_estoque', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
                'ordering': ['material__nome'],
                'constraints': [models.UniqueConstraint(fields=('material', 'unidade'), name='wks_saldo_unico_por_unidade'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='wks_saldo_nao_negativo')],
            },
        ),
    ]
