# Generated by Django 6.0.7 on 2026-08-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0029_material_movimentoestoque_saldoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias', to='workspace.anexo'),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='empresa',
            field=models.CharField(blank=True, help_text='Correios, transportadora, cartório.', max_length=120),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='numero_rastreio',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
