# Generated by Django 6.0.7 on 2026-08-18 21:34

import workspace.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0030_correspondencia_anexo_correspondencia_confirmado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='anexo',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='foto',
            field=models.FileField(blank=True, max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_da_correspondencia),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='anexo',
            field=models.FileField(blank=True, help_text='PDF da política, ata, planilha.', max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_da_imagem),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='arquivado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Em branco, alcança todos os departamentos.', related_name='publicacoes', to='identidade.departamento'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.FileField(blank=True, max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_da_imagem),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='unidades',
            field=models.ManyToManyField(blank=True, help_text='Em branco, alcança todas as unidades.', related_name='publicacoes', to='identidade.unidade'),
        ),
    ]
