# Generated by Django 6.0.7 on 2026-08-18 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0031_remove_correspondencia_anexo_correspondencia_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('rh', 'RH'), ('ops', 'Operações'), ('log', 'Suprimentos'), ('com', 'Compras'), ('fin', 'Financeiro'), ('ti', 'TI e Redes'), ('mkt', 'Marketing'), ('jur', 'Jurídico'), ('hab', 'Universidade'), ('ven', 'Vendas'), ('doc', 'Documentos'), ('res', 'Reservas'), ('proc', 'Processos internos')], db_index=True, max_length=10)),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField()),
                ('palavras_chave', models.JSONField(blank=True, default=list, help_text='Como as pessoas perguntam isto. Um por linha.')),
                ('url_acao', models.CharField(blank=True, help_text='Caminho interno. Ex.: /workspace/servicos/ferias/', max_length=300)),
                ('rotulo_acao', models.CharField(blank=True, max_length=60)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pergunta frequente',
                'verbose_name_plural': 'perguntas frequentes',
                'ordering': ['area', '-prioridade', 'pergunta'],
                'indexes': [models.Index(fields=['ativo', 'area', '-prioridade'], name='wks_faq_area_idx')],
            },
        ),
    ]
