# Generated by Django 6.0.7 on 2026-08-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0032_perguntafrequente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='modulos_extras',
            field=models.JSONField(blank=True, default=list, help_text='Chaves de módulo onde o item também aparece. Ex.: ["rh"]'),
        ),
    ]
