# Generated by Django 6.0.7 on 2026-08-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0034_rh_reorganizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Preenchido, o card abre este endereço em vez do formulário.', max_length=300),
        ),
    ]
