# Generated by Django 6.0.7 on 2026-08-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0035_itemcatalogo_url_externa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcatalogo',
            name='modulos_extras',
        ),
    ]
