# Generated by Django 6.0.7 on 2026-08-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0037_reembolso_e_pj_no_rh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('habilitacao_a_vencer', 'Habilitação vencendo ou vencida'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('tipo', models.CharField(choices=[('nr', 'Norma regulamentadora'), ('tecnico', 'Técnico'), ('institucional', 'Institucional'), ('integracao', 'Integração')], db_index=True, default='tecnico', max_length=20)),
                ('carga_horaria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validade_meses', models.PositiveSmallIntegerField(default=0, help_text='0 = não vence.')),
                ('obrigatorio', models.BooleanField(default=False, help_text='Aparece como pendência de quem for matriculado.')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['ativo', 'tipo'], name='wks_curso_idx')],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('dispensado', 'Dispensado')], db_index=True, default='pendente', max_length=20)),
                ('percentual', models.PositiveSmallIntegerField(default=0)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluido_em', models.DateField(blank=True, null=True)),
                ('vence_em', models.DateField(blank=True, db_index=True, null=True)),
                ('certificado', models.CharField(blank=True, help_text='Número ou identificação do certificado.', max_length=120)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='workspace.curso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ['vence_em', 'prazo', 'curso__nome'],
                'indexes': [models.Index(fields=['situacao', 'vence_em'], name='wks_matricula_venc_idx'), models.Index(fields=['pessoa', 'situacao'], name='wks_matricula_pessoa_idx')],
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'curso'), name='wks_matricula_unica')],
            },
        ),
    ]
