# Generated by Django 6.0.7 on 2026-08-19 00:36

import workspace.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0038_alter_notificacao_tipo_curso_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_do_documento),
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_nome',
            field=models.CharField(blank=True, help_text='Nome original, para quem baixa reconhecer.', max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_tamanho',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
