# Generated by Django 6.0.7 on 2026-08-19 00:37

import django.db.models.deletion
import django.utils.timezone
import workspace.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0039_documento_arquivo_documento_arquivo_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrega', 'Relatório de entrega'), ('ocorrencia', 'Relatório de ocorrência (CSI)')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=160)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('ocorrido_em', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitido', 'Emitido'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('emitido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
                'ordering': ['-ocorrido_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=255, storage=workspace.storage.ArmazenamentoPrivado(), upload_to=workspace.storage.caminho_do_documento)),
                ('nome_original', models.CharField(max_length=255)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='workspace.relatorio')),
            ],
            options={
                'verbose_name': 'evidência',
                'verbose_name_plural': 'evidências',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['tipo', 'situacao', '-ocorrido_em'], name='wks_rel_lista_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorio',
            index=models.Index(fields=['autor', '-criado_em'], name='wks_rel_autor_idx'),
        ),
    ]
