# Generated by Django 6.0.7 on 2026-08-19 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0041_alter_notificacao_tipo_comentariosolicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('comentario_no_pedido', 'Comentaram no seu pedido'), ('habilitacao_a_vencer', 'Habilitação vencendo ou vencida'), ('equipamento_sob_custodia', 'Um equipamento está sob sua responsabilidade'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('patrimonio', models.CharField(blank=True, db_index=True, max_length=40)),
                ('numero_serie', models.CharField(blank=True, max_length=60)),
                ('entregue_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('devolvido_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('condicao_devolucao', models.CharField(blank=True, choices=[('novo', 'Novo'), ('usado_bom', 'Usado — em boas condições'), ('usado_reparo', 'Usado — precisa de reparo'), ('sucata', 'Sucata')], max_length=15)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('devolvido_por', models.ForeignKey(blank=True, help_text='Quem recebeu de volta — Suprimentos, não a pessoa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias_entregues', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='workspace.material')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'custódia',
                'verbose_name_plural': 'custódias',
                'ordering': ['-entregue_em'],
                'indexes': [models.Index(fields=['pessoa', 'devolvido_em'], name='wks_custodia_pessoa_idx'), models.Index(fields=['unidade', 'devolvido_em'], name='wks_custodia_unid_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='wks_custodia_quantidade')],
            },
        ),
    ]
