# Generated by Django 6.0.7 on 2026-08-19 13:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidade', '0001_initial'),
        ('workspace', '0042_alter_notificacao_tipo_custodia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('comentario_no_pedido', 'Comentaram no seu pedido'), ('habilitacao_a_vencer', 'Habilitação vencendo ou vencida'), ('equipamento_sob_custodia', 'Um equipamento está sob sua responsabilidade'), ('documento_de_veiculo', 'Documento de veículo vencendo ou vencido'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('marca', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(max_length=60)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('utilitario', 'Utilitário'), ('van', 'Van'), ('moto', 'Moto'), ('caminhao', 'Caminhão')], default='carro', max_length=15)),
                ('renavam', models.CharField(blank=True, max_length=20)),
                ('chassi', models.CharField(blank=True, max_length=25)),
                ('km_atual', models.PositiveIntegerField(default=0)),
                ('licenciamento_ate', models.DateField(blank=True, null=True)),
                ('seguro_ate', models.DateField(blank=True, null=True)),
                ('ipva_ate', models.DateField(blank=True, null=True)),
                ('revisao_em', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('ativo', 'Em operação'), ('manutencao', 'Em manutenção'), ('baixado', 'Baixado')], db_index=True, default='ativo', max_length=15)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.OneToOneField(blank=True, help_text='O recurso reservável correspondente, quando o carro é de uso comum.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo', to='workspace.recurso')),
                ('unidade', models.ForeignKey(blank=True, help_text='Onde o veículo fica lotado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='identidade.unidade')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='DespesaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustivel', 'Combustível'), ('pedagio', 'Pedágio'), ('estacionamento', 'Estacionamento'), ('lavagem', 'Lavagem'), ('manutencao', 'Manutenção'), ('multa', 'Multa')], db_index=True, max_length=15)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('tanque_cheio', models.BooleanField(default=True)),
                ('fornecedor', models.CharField(blank=True, max_length=120)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quem', models.ForeignKey(blank=True, help_text='Quem lançou — não necessariamente quem dirigia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_veiculo', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='workspace.veiculo')),
            ],
            options={
                'verbose_name': 'despesa de veículo',
                'verbose_name_plural': 'despesas de veículo',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['situacao', 'unidade'], name='wks_veiculo_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaveiculo',
            index=models.Index(fields=['veiculo', '-data'], name='wks_desp_veic_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaveiculo',
            index=models.Index(fields=['tipo', '-data'], name='wks_desp_tipo_idx'),
        ),
    ]
