# Generated by Django 6.0.7 on 2026-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0044_veiculo_so_na_grade_de_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosolicitacao',
            name='acao',
            field=models.CharField(choices=[('rascunho_guardado', 'Rascunho guardado'), ('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('etapa_aprovada', 'Aprovado num degrau'), ('aprovada', 'Aprovado — liberado'), ('devolvida', 'Devolvido para quem pediu'), ('rejeitada', 'Reprovado'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('reaberta', 'Reaberto — não resolveu'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='situacao',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('em_atendimento', 'Em atendimento'), ('concluida', 'Concluída'), ('devolvida', 'Devolvida'), ('rejeitada', 'Reprovada'), ('cancelada', 'Cancelada')], db_index=True, default='aguardando_aprovacao', max_length=25),
        ),
    ]
