# Generated by Django 6.0.7 on 2026-08-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0046_alter_notificacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('comentario_no_pedido', 'Comentaram no seu pedido'), ('habilitacao_a_vencer', 'Habilitação vencendo ou vencida'), ('equipamento_sob_custodia', 'Um equipamento está sob sua responsabilidade'), ('prazo_de_oportunidade', 'Prazo para decidir sobre uma oportunidade'), ('leitura_obrigatoria', 'Documento com leitura obrigatória'), ('documento_a_vencer', 'Documento vencendo ou vencido'), ('documento_de_veiculo', 'Documento de veículo vencendo ou vencido'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('feira', 'Feira ou exposição'), ('congresso', 'Congresso ou seminário'), ('patrocinio', 'Patrocínio'), ('premio', 'Prêmio ou selo'), ('midia', 'Mídia ou publicidade'), ('parceria', 'Parceria ou associação')], default='feira', max_length=15)),
                ('organizador', models.CharField(blank=True, max_length=160)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('site', models.URLField(blank=True, max_length=300)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('prazo_decisao', models.DateField(blank=True, help_text='Até quando é preciso responder.', null=True)),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('publico_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('retorno_esperado', models.TextField(blank=True)),
                ('origem', models.CharField(blank=True, help_text='Como a empresa soube — e-mail, cliente, feira anterior.', max_length=200)),
                ('situacao', models.CharField(choices=[('radar', 'No radar'), ('avaliando', 'Em avaliação'), ('aprovada', 'Aprovada — pedido aberto'), ('descartada', 'Descartada'), ('realizada', 'Realizada')], db_index=True, default='radar', max_length=15)),
                ('motivo', models.CharField(blank=True, help_text='Por que foi descartada, ou o que decidiu.', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='workspace.solicitacaoservico')),
            ],
            options={
                'verbose_name': 'oportunidade de marketing',
                'verbose_name_plural': 'oportunidades de marketing',
                'ordering': [models.OrderBy(models.F('prazo_decisao'), nulls_last=True), '-criado_em'],
                'indexes': [models.Index(fields=['situacao', 'prazo_decisao'], name='wks_oport_idx')],
            },
        ),
    ]
