# Generated by Django 6.0.7 on 2026-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0047_alter_notificacao_tipo_oportunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaindice',
            name='origem',
            field=models.CharField(choices=[('servico', 'Serviços'), ('solicitacao', 'Minhas solicitações'), ('documento', 'Documentação'), ('faq', 'Perguntas frequentes'), ('curso', 'Universidade'), ('recurso', 'Reservas'), ('correspondencia', 'Correspondências'), ('comunicado', 'Comunicados'), ('noticia', 'Notícias')], db_index=True, max_length=20),
        ),
    ]
