# Generated by Django 6.0.7 on 2026-08-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0048_alter_entradaindice_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaveiculo',
            name='destino',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='despesaveiculo',
            name='finalidade',
            field=models.CharField(blank=True, help_text='Cliente, obra, entrega, deslocamento.', max_length=200),
        ),
        migrations.AddField(
            model_name='despesaveiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, help_text='Quem estava dirigindo. Vazio quando não se sabe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_dirigidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
