# Generated by Django 6.0.7 on 2026-08-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0049_despesaveiculo_destino_despesaveiculo_finalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
