# Generated by Django 6.0.8 on 2026-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0050_documento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosolicitacao',
            name='acao',
            field=models.CharField(choices=[('rascunho_guardado', 'Rascunho guardado'), ('criada', 'Pedido aberto'), ('auto_aprovada', 'Aprovado automaticamente'), ('etapa_aprovada', 'Aprovado num degrau'), ('aprovada', 'Aprovado — liberado'), ('devolvida', 'Devolvido para quem pediu'), ('rejeitada', 'Reprovado'), ('cancelada', 'Cancelado'), ('assumida', 'Atendimento assumido'), ('concluida', 'Concluído'), ('reaberta', 'Reaberto — não resolveu'), ('reenviada', 'Reenviado depois de corrigir'), ('acerto', 'Acerto do adiantamento confirmado')], max_length=20),
        ),
    ]
