# Generated by Django 6.0.8 on 2026-09-02 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0051_reenvio_de_pedido_devolvido'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao_curta', models.CharField(help_text='O que a regra procura, em uma frase. Aparece na lista.', max_length=300)),
                ('severidade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], db_index=True, default='media', max_length=10)),
                ('janela', models.PositiveSmallIntegerField(default=0)),
                ('escopo_papel', models.CharField(blank=True, db_index=True, max_length=40)),
                ('fonte_requerida', models.CharField(blank=True, max_length=30)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'regra de exceção',
                'verbose_name_plural': 'regras de exceção',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executada_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total', models.PositiveIntegerField(default=0)),
                ('chaves', models.JSONField(blank=True, default=list)),
                ('avaliada', models.BooleanField(default=True)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='workspace.regraexcecao')),
            ],
            options={
                'verbose_name': 'resultado de exceção',
                'verbose_name_plural': 'resultados de exceção',
                'ordering': ['-executada_em'],
                'indexes': [models.Index(fields=['regra', '-executada_em'], name='wks_excecao_hist_idx')],
            },
        ),
    ]
