# Generated by Django 6.0.8 on 2026-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0052_regraexcecao_resultadoexcecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('vez_de_aprovar', 'Chegou sua vez de aprovar'), ('pedido_aprovado', 'Seu pedido foi aprovado'), ('pedido_devolvido', 'Seu pedido foi devolvido'), ('pedido_rejeitado', 'Seu pedido foi reprovado'), ('pedido_cancelado', 'Seu pedido foi cancelado'), ('pedido_em_atendimento', 'Seu pedido está sendo atendido'), ('pedido_concluido', 'Seu pedido foi concluído'), ('pedido_reaberto', 'Um pedido que você atendeu foi reaberto'), ('pedido_na_fila', 'Chegou um pedido para a sua área'), ('aprovacao_sem_dono', 'Um pedido parou num papel sem ninguém'), ('comentario_no_pedido', 'Comentaram no seu pedido'), ('habilitacao_a_vencer', 'Habilitação vencendo ou vencida'), ('equipamento_sob_custodia', 'Um equipamento está sob sua responsabilidade'), ('prazo_de_oportunidade', 'Prazo para decidir sobre uma oportunidade'), ('leitura_obrigatoria', 'Documento com leitura obrigatória'), ('documento_a_vencer', 'Documento vencendo ou vencido'), ('excecao_aberta', 'Uma regra de exceção exige atenção'), ('documento_de_veiculo', 'Documento de veículo vencendo ou vencido'), ('correspondencia_recebida', 'Chegou correspondência para você')], db_index=True, max_length=30),
        ),
    ]
