# Generated by Django 6.0.8 on 2026-09-02 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0053_alter_notificacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cadencia', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral')], default='mensal', max_length=12)),
                ('publico', models.CharField(blank=True, max_length=200)),
                ('papeis_leitores', models.JSONField(blank=True, default=list)),
                ('papel_condutor', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ciclo de planejamento',
                'verbose_name_plural': 'ciclos de planejamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('pop', 'POP — procedimento operacional'), ('politica', 'Política'), ('norma', 'Norma'), ('instrucao', 'Instrução de trabalho'), ('manual', 'Manual'), ('ata', 'ATA de ciclo')], db_index=True, default='pop', max_length=20),
        ),
        migrations.CreateModel(
            name='EtapaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('titulo', models.CharField(max_length=160)),
                ('tela', models.CharField(blank=True, max_length=8)),
                ('pergunta', models.CharField(blank=True, max_length=300)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workspace.cicloplanejamento')),
            ],
            options={
                'verbose_name': 'etapa de ciclo',
                'verbose_name_plural': 'etapas de ciclo',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], db_index=True, default='aberta', max_length=10)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('impedimentos', models.JSONField(blank=True, default=list)),
                ('ata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ata_de', to='workspace.documento')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='workspace.cicloplanejamento')),
                ('conduzida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_conduzidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ocorrência de ciclo',
                'verbose_name_plural': 'ocorrências de ciclo',
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='AnotacaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('encaminhamento', models.CharField(blank=True, max_length=300)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('carimbo_fonte', models.CharField(blank=True, max_length=40)),
                ('carimbo_texto', models.CharField(blank=True, max_length=200)),
                ('carimbo_alerta', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes_de_ciclo', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='workspace.etapaciclo')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='workspace.ocorrenciaciclo')),
            ],
            options={
                'verbose_name': 'anotação de etapa',
                'verbose_name_plural': 'anotações de etapa',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='etapaciclo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'codigo'), name='wks_etapa_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='ocorrenciaciclo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'ano', 'mes'), name='wks_ocorrencia_competencia_unica'),
        ),
    ]
