# Generated by Django 6.0.8 on 2026-09-02 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0054_ciclo_de_planejamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regraexcecao',
            name='exige_plano',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='regraexcecao',
            name='prazo_do_plano',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra_chave', models.SlugField(max_length=60)),
                ('ocorrencia_chave', models.CharField(db_index=True, max_length=120)),
                ('titulo', models.CharField(max_length=200)),
                ('detalhe', models.CharField(blank=True, max_length=300)),
                ('justificativa', models.TextField()),
                ('acao', models.TextField()),
                ('prazo', models.DateField(db_index=True)),
                ('situacao', models.CharField(choices=[('aberto', 'Em andamento'), ('resolvido', 'Resolvido'), ('nao_resolvido', 'Não resolvido')], db_index=True, default='aberto', max_length=15)),
                ('desfecho', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('aberto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_abertos', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano de ação',
                'verbose_name_plural': 'planos de ação',
                'ordering': ['prazo', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VerificacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ainda_ocorre', models.BooleanField()),
                ('avaliada', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='workspace.planoacao')),
            ],
            options={
                'verbose_name': 'verificação de plano',
                'verbose_name_plural': 'verificações de plano',
                'ordering': ['-verificado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='planoacao',
            index=models.Index(fields=['situacao', 'prazo'], name='wks_plano_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='planoacao',
            constraint=models.UniqueConstraint(condition=models.Q(('situacao', 'aberto')), fields=('regra_chave', 'ocorrencia_chave'), name='wks_plano_um_aberto_por_ocorrencia'),
        ),
    ]
