# Generated by Django 6.0.8 on 2026-09-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0055_plano_de_acao_com_limiar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto — definindo metas'), ('em_curso', 'Em curso'), ('fechado', 'Fechado')], db_index=True, default='aberto', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ciclo de metas',
                'verbose_name_plural': 'ciclos de metas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidades', models.TextField(blank=True)),
                ('interesses', models.TextField(blank=True)),
                ('aspiracao_curta', models.TextField(blank=True)),
                ('aspiracao_longa', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_desenvolvimento', to='workspace.ciclometas')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano de desenvolvimento',
                'verbose_name_plural': 'planos de desenvolvimento',
                'ordering': ['-ciclo__inicio'],
            },
        ),
        migrations.CreateModel(
            name='AcaoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('concluida_em', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='workspace.planodesenvolvimento')),
            ],
            options={
                'verbose_name': 'ação de desenvolvimento',
                'verbose_name_plural': 'ações de desenvolvimento',
                'ordering': ['ano', 'mes', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuadroMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('apurado', 'Apurado')], db_index=True, default='rascunho', max_length=10)),
                ('resumo', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('apurado_em', models.DateTimeField(blank=True, null=True)),
                ('reaberturas', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_aprovados', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='workspace.ciclometas')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quadro de metas',
                'verbose_name_plural': 'quadros de metas',
                'ordering': ['-ciclo__inicio', 'pessoa__nome'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('financeira', 'Metas financeiras'), ('operacional', 'Metas operacionais'), ('pessoas', 'Metas de pessoas'), ('projeto', 'Metas de projeto')], default='financeira', max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('detalhamento', models.TextField(blank=True)),
                ('peso', models.PositiveSmallIntegerField(default=1)),
                ('fator_1', models.CharField(max_length=40)),
                ('fator_2', models.CharField(blank=True, max_length=40)),
                ('tipo_calculo', models.CharField(choices=[('direto', 'Diretamente proporcional'), ('inverso', 'Inversamente proporcional')], default='direto', max_length=10)),
                ('alvo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('atingimento_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('motivo_sem_apuracao', models.CharField(blank=True, max_length=200)),
                ('carimbo_texto', models.CharField(blank=True, max_length=200)),
                ('apurado_em', models.DateTimeField(blank=True, null=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='workspace.quadrometas')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['grupo', 'ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planodesenvolvimento',
            constraint=models.UniqueConstraint(fields=('ciclo', 'pessoa'), name='wks_pdi_um_por_ciclo'),
        ),
        migrations.AddConstraint(
            model_name='quadrometas',
            constraint=models.UniqueConstraint(fields=('ciclo', 'pessoa'), name='wks_quadro_um_por_ciclo'),
        ),
    ]
