# Generated by Django 6.0.8 on 2026-09-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0057_liga_conciliacao_de_centro_de_custo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(choices=[('contrato', 'Contrato'), ('area', 'Área'), ('indicador', 'Indicador')], db_index=True, max_length=20)),
                ('origem_ref', models.CharField(db_index=True, max_length=60)),
                ('titulo', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('prazo', models.DateField(blank=True, db_index=True, null=True)),
                ('aberta_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encerrada_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resultado', models.TextField(blank=True)),
                ('aberta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concentracoes_abertas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concentracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'concentração',
                'verbose_name_plural': 'concentrações',
                'ordering': ['encerrada_em', 'prazo', '-aberta_em'],
                'indexes': [models.Index(fields=['encerrada_em', 'prazo'], name='wks_conc_abertas_idx'), models.Index(fields=['origem_tipo', 'origem_ref'], name='wks_conc_origem_idx')],
            },
        ),
    ]
