# Generated by Django 6.0.8 on 2026-09-14 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0058_concentracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concentracao',
            name='alerta_chave',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='concentracao',
            name='proximo_passo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='concentracao',
            constraint=models.UniqueConstraint(condition=models.Q(('encerrada_em__isnull', True), models.Q(('alerta_chave', ''), _negated=True)), fields=('alerta_chave',), name='wks_conc_alerta_aberto_unico'),
        ),
    ]
