# Generated by Django 6.0.8 on 2026-09-22 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0059_concentracao_acompanhamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('telefone_planilha', models.CharField(blank=True, help_text='Como veio no arquivo, para o R.H. reconhecer.', max_length=60)),
                ('telefone_normalizado', models.CharField(blank=True, max_length=20)),
                ('telefone_corrigido', models.CharField(blank=True, max_length=20)),
                ('pendencias', models.JSONField(blank=True, default=list)),
                ('quantidade_pendencias', models.PositiveSmallIntegerField(default=0)),
                ('selecionado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'colaborador do lote',
                'verbose_name_plural': 'colaboradores do lote',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LotePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_bytes', models.PositiveIntegerField(default=0)),
                ('arquivo_digest', models.CharField(blank=True, help_text='SHA-256 do arquivo — reconhece a mesma planilha importada duas vezes.', max_length=64)),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('validando', 'Validando'), ('validado', 'Validado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('concluido_com_erros', 'Concluído com erros'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('modo', models.CharField(choices=[('teste', 'Teste'), ('producao', 'Produção')], default='teste', max_length=10)),
                ('telefone_teste', models.CharField(blank=True, max_length=20)),
                ('erro_validacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('quem_importou', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_de_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lote de pendências de ponto',
                'verbose_name_plural': 'lotes de pendências de ponto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('upload', 'Planilha enviada'), ('validacao', 'Planilha validada'), ('alteracao_telefone', 'Telefone corrigido'), ('teste_solicitado', 'Teste solicitado'), ('teste_executado', 'Teste executado'), ('producao_confirmada', 'Envio real confirmado'), ('envio_real_iniciado', 'Envio real iniciado'), ('envio_concluido', 'Envio concluído'), ('envio_falhou', 'Envio falhou'), ('cancelamento', 'Lote cancelado')], max_length=24)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalhe', models.CharField(blank=True, max_length=400)),
                ('quando', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_de_ponto', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='workspace.loteponto')),
            ],
            options={
                'verbose_name': 'evento do lote de ponto',
                'verbose_name_plural': 'eventos do lote de ponto',
                'ordering': ['quando', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EnvioPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('teste', 'Teste'), ('producao', 'Produção')], max_length=10)),
                ('destino', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=12)),
                ('erro', models.TextField(blank=True)),
                ('resposta', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='workspace.colaboradorponto')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='workspace.loteponto')),
            ],
            options={
                'verbose_name': 'envio de pendência de ponto',
                'verbose_name_plural': 'envios de pendência de ponto',
                'ordering': ['colaborador__nome', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='colaboradorponto',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='workspace.loteponto'),
        ),
        migrations.AddIndex(
            model_name='loteponto',
            index=models.Index(fields=['situacao', '-criado_em'], name='wks_ponto_lote_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoponto',
            index=models.Index(fields=['lote', 'quando'], name='wks_ponto_evento_idx'),
        ),
        migrations.AddIndex(
            model_name='envioponto',
            index=models.Index(fields=['lote', 'situacao'], name='wks_ponto_envio_idx'),
        ),
        migrations.AddIndex(
            model_name='colaboradorponto',
            index=models.Index(fields=['lote', 'nome'], name='wks_ponto_colab_idx'),
        ),
    ]
