# Generated by Django 6.0.8 on 2026-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0060_colaboradorponto_loteponto_eventoponto_envioponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='rota_interna',
            field=models.CharField(blank=True, help_text='Nome da rota Django. Preenchido, o card abre essa tela em vez do formulário.', max_length=100),
        ),
    ]
