# Generated by Django 6.0.8 on 2026-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0061_itemcatalogo_rota_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='categoria',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
